name: Deploy Laravel to Render

on:
  push:
    branches:
      - main  # O la rama que estés usando para el despliegue

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Checkout del código
      - name: Checkout code
        uses: actions/checkout@v2

      # Paso 2: Configurar PHP
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      # Paso 3: Instalar dependencias de PHP
      - name: Install dependencies
        run: |
          npm install
          npm run build

      # Paso 4: Ejecutar las migraciones
      - name: Run migrations
        run: php artisan migrate --force

      # Paso 5: Ejecutar los seeders
      - name: Run seeders
        run: |
          php artisan db:seed --class=CategorySeeder
          php artisan db:seed --class=ProductSeeder
          php artisan db:seed --class=RolePermissionSeeder

      # Paso 6: Desplegar a Render
      - name: Deploy to Render
        run: |
          render deploy
